# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: AzureKeyVault@1
  inputs:
    ConnectedServiceName: 'Azure'
    KeyVaultName: 'kv-sw5eweb-dev'

- task: YarnInstaller@2
  inputs:
    versionSpec: '1.x'
    checkLatest: true
  displayName: 'Install Yarn'

# - task: Yarn@2
#   inputs:
#     Arguments: 'build'
#     ProductionMode: true
#   displayName: 'Install Yarn'

# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: yarn; yarn build;
  displayName: 'Install Packages and Build'
  # env:
  #   sw5eapiurl: $(sw5eapiurl)
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  inputs:
    ArtifactName: 'drop'
